### ISSUE TITLE
Not logging request json?

### ISSUE THREAD

**Issue by tuckerconnelly** [onbjerg/micro-visualize#10]
https://github.com/onbjerg/micro-visualize/commit/6fb7dda40317b5e41360dd8f2db523e67f39ab9f#diff-168726dbe96b3ce427e7fedce31bb0bcR19

Did you mean `req.headers['content-type']`?

**Comment by onbjerg** [comment]
Oh crap, you're right. Sorry for the inconvenience and thank you for spotting it.

I've fixed it in v3.0.1.

**Comment by tuckerconnelly** [comment]
Mmmmm something funky is going on. It hangs up on https://github.com/onbjerg/micro-visualize/blob/master/index.js#L21 , and then throws "Invalid body" https://github.com/zeit/micro/blob/master/lib/server.js#L74 on some requests

I think it's when another middleware returns out without calling next function.

Couldn't figure it out quickly, gonna move back to 3.0.0

**Comment by onbjerg** [comment]
Hmm, I'll check it out later. Thanks 😄 

Actually, maybe I should write some simple tests for this.

**Comment by tuckerconnelly** [comment]
@onbjerg Got it, was my bad :) Developing lib, which also calls `await json(req)`, but had micro as a dependency instead of as a peer dependency, so it was trying to pull the text from the req stream twice.

**Comment by onbjerg** [comment]
@tuckerconnelly Glad to hear it! Good luck with your library 😄
