### ISSUE TITLE
Bump up micro version to 7

### ISSUE THREAD

**Issue by tuckerconnelly** [onbjerg/micro-visualize#8]

**Comment by onbjerg** [comment]
Hey! Do you know if it still works with 7? Sorry for the wait, just got back from holidays 😄

**Comment by tuckerconnelly** [comment]
Working fine over here!

**Comment by onbjerg** [comment]
Hey, sorry, we already depend on micro ^7.1.0? 🤔 I'll close this, tell me if I misunderstood 😊
